export const MAJOR_ARCANA = [
  { name: "Le Mat", up: "Élan, liberté, départ, spontanéité", rev: "Errance, imprudence, dispersion" },
  { name: "Le Bateleur (I)", up: "Initiative, potentiel, habileté", rev: "Dispersion, maladresse, manipulation" },
  { name: "La Papesse (II)", up: "Intuition, intériorité, connaissance", rev: "Secret, passivité, blocage" },
  { name: "L’Impératrice (III)", up: "Créativité, intelligence, expression", rev: "Excès mental, instabilité, superficialité" },
  { name: "L’Empereur (IV)", up: "Structure, stabilité, autorité", rev: "Rigidité, contrôle, domination" },
  { name: "Le Pape (V)", up: "Transmission, conseil, tradition", rev: "Dogmatisme, conformisme, dépendance" },
  { name: "L’Amoureux (VI)", up: "Choix, relation, désir", rev: "Indécision, conflit affectif, dispersion" },
  { name: "Le Chariot (VII)", up: "Avancée, maîtrise, victoire", rev: "Précipitation, perte de direction, blocage" },
  { name: "La Justice (VIII)", up: "Équilibre, vérité, décision", rev: "Injustice, déséquilibre, jugement sévère" },
  { name: "L’Hermite (IX)", up: "Prudence, recherche, maturation", rev: "Isolement, lenteur, fermeture" },
  { name: "La Roue de Fortune (X)", up: "Cycle, changement, évolution", rev: "Résistance, répétition, instabilité" },
  { name: "La Force (XI)", up: "Courage, énergie, maîtrise de soi", rev: "Impulsivité, tension, manque de confiance" },
  { name: "Le Pendu (XII)", up: "Lâcher-prise, attente, nouveau regard", rev: "Blocage, sacrifice stérile, immobilisme" },
  { name: "L’Arcane sans nom (XIII)", up: "Transformation, fin de cycle, renouvellement", rev: "Résistance au changement, peur de la rupture" },
  { name: "Tempérance (XIV)", up: "Équilibre, circulation, apaisement", rev: "Excès, impatience, déséquilibre" },
  { name: "Le Diable (XV)", up: "Désir, puissance, attachement", rev: "Dépendance, emprise, excès" },
  { name: "La Maison Dieu (XVI)", up: "Libération, bouleversement, révélation", rev: "Crise retardée, peur du changement, fragilité" },
  { name: "L’Étoile (XVII)", up: "Espoir, inspiration, simplicité", rev: "Doute, vulnérabilité, perte de confiance" },
  { name: "La Lune (XVIII)", up: "Intuition, imaginaire, sensibilité", rev: "Confusion, peur, illusion" },
  { name: "Le Soleil (XIX)", up: "Clarté, joie, réussite", rev: "Orgueil, surexposition, excès de confiance" },
  { name: "Le Jugement (XX)", up: "Réveil, appel, prise de conscience", rev: "Hésitation, jugement de soi, retard" },
  { name: "Le Monde (XXI)", up: "Accomplissement, unité, ouverture", rev: "Inachèvement, dispersion, clôture difficile" }
]
