export const SITE_URL = 'https://www.1001perspectives.com'

export const INTENT_PAGES = {
  fr: [
    {slug:'tarot-de-marseille', title:'Tarot de Marseille : tirage et interprétation en ligne', description:'Découvrez le Tarot de Marseille, ses arcanes majeurs et réalisez un tirage en ligne pour éclairer une question personnelle.', h1:'Tarot de Marseille : comprendre les cartes et réaliser un tirage', intro:'Le Tarot de Marseille est un langage symbolique composé d’images, de nombres et d’archétypes. Sur 1001 Perspectives, vous pouvez explorer les arcanes majeurs puis réaliser un tirage en ligne pour nourrir votre réflexion.', sections:[['Comment fonctionne un tirage ?','Vous formulez une question précise, choisissez un tirage puis sélectionnez vos cartes. L’interprétation met en relation la symbolique de chaque arcane avec la place qu’il occupe dans le tirage.'],['Les 22 arcanes majeurs','Les arcanes majeurs décrivent des dynamiques fortes : commencement, choix, transformation, maîtrise, attente, accomplissement. Chaque carte possède plusieurs niveaux de lecture selon le contexte.'],['Une lecture symbolique','Le tarot ne remplace ni un avis médical, juridique ou financier, ni une décision personnelle. Il s’utilise ici comme support de réflexion et de mise en perspective.']]},
    {slug:'tirage-tarot-en-ligne', title:'Tirage tarot en ligne : 1, 3 ou 5 cartes', description:'Réalisez un tirage de Tarot de Marseille en ligne : une carte, passé-présent-futur ou croix simple, avec interprétation personnalisée.', h1:'Tirage de tarot en ligne', intro:'Choisissez le format adapté à votre question : une carte pour un message essentiel, trois cartes pour une dynamique temporelle, ou cinq cartes pour une lecture plus nuancée.', sections:[['Tirage à une carte','Idéal pour clarifier une tendance, une énergie dominante ou une question simple.'],['Tirage à trois cartes','Le format passé – présent – futur permet d’observer une évolution et les liens entre les étapes.'],['Tirage à cinq cartes','La croix simple approfondit les tensions, les soutiens, la direction et le centre de la question.']]},
    {slug:'tirage-amour', title:'Tarot amour : tirage sentimental avec le Tarot de Marseille', description:'Explorez une question sentimentale avec un tirage de Tarot de Marseille : relation, rencontre, évolution et choix amoureux.', h1:'Tarot amour et questions sentimentales', intro:'Un tirage amoureux aide à mettre en perspective une relation, une attente, un choix ou une période de transition. Il ne prétend pas connaître avec certitude les pensées ou actes futurs d’un tiers.', sections:[['Formuler une bonne question','Préférez une question ouverte et centrée sur votre situation : « Quelle dynamique dois-je comprendre ? » plutôt que « Va-t-il revenir ? ».'],['Cartes souvent marquantes en amour','Les Amoureux, l’Impératrice, le Soleil, la Lune ou le Diable prennent des nuances particulières selon les cartes qui les entourent.'],['Garder votre libre arbitre','Le tirage propose un angle de réflexion. Vous restez responsable de vos décisions et de vos relations.']]},
    {slug:'tirage-travail', title:'Tarot travail : carrière, évolution et choix professionnels', description:'Utilisez le Tarot de Marseille pour réfléchir à une évolution professionnelle, un choix de carrière ou une période de changement.', h1:'Tarot travail et évolution professionnelle', intro:'Le tarot peut servir de support pour clarifier vos priorités face à un choix professionnel, une transition, un projet ou une situation de blocage.', sections:[['Questions professionnelles','Interrogez le contexte, vos ressources, vos freins et les options qui s’ouvrent plutôt que de rechercher une prédiction certaine.'],['Arcanes et dynamique professionnelle','Le Chariot peut évoquer l’élan, l’Empereur la structure, la Roue de Fortune le changement, le Monde l’accomplissement.'],['Pas un conseil financier ou juridique','Une lecture symbolique ne remplace jamais un professionnel qualifié pour une décision contractuelle, fiscale, juridique ou financière.']]},
    {slug:'consultation-tarologue', title:'Consultation de tarot en ligne avec Nanou', description:'Prolongez votre tirage par une consultation privée en ligne avec Nanou lorsque le service est disponible.', h1:'Consultation privée de tarot avec Nanou', intro:'Après votre tirage, vous pouvez approfondir vos questions dans un échange privé avec Nanou lorsque la consultation est ouverte. Les conditions tarifaires sont toujours affichées avant tout paiement.', sections:[['Une consultation personnalisée','La consultation reprend votre question et le contexte de votre tirage afin d’approfondir les symboles et les pistes de réflexion.'],['Disponibilité','Le chat peut être fermé lorsque Nanou n’est pas disponible. Aucun paiement de consultation privée n’est alors possible.'],['Transparence tarifaire','Le prix, la durée et les modalités de renouvellement sont présentés avant validation du paiement.']]}
  ],
  en: [
    {slug:'marseille-tarot', title:'Marseille Tarot: online reading and card meanings', description:'Explore the Marseille Tarot major arcana and use an online spread to reflect on a personal question.', h1:'Marseille Tarot: cards, symbols and online readings', intro:'The Marseille Tarot is a symbolic language built from images, numbers and archetypes. 1001 Perspectives lets you explore the major arcana and use a spread as a structured reflection tool.', sections:[['How a reading works','Write a clear question, choose a spread and select your cards. The interpretation connects each card’s symbolism with its position in the spread.'],['The 22 Major Arcana','The Major Arcana describe strong themes such as beginnings, choices, transformation, self-mastery, waiting and completion.'],['Symbolic guidance','Tarot does not replace medical, legal or financial advice and should not be treated as a guaranteed prediction.']]},
    {slug:'online-tarot-reading', title:'Online Tarot reading: 1, 3 or 5 cards', description:'Try an online Marseille Tarot spread with one card, past-present-future, or a five-card cross.', h1:'Online Tarot reading', intro:'Choose a spread that fits your question: one card for a concise focus, three cards for a timeline, or five cards for a more detailed perspective.', sections:[['One-card spread','Useful for identifying a dominant theme or reflecting on a focused question.'],['Three-card spread','Past – present – future highlights movement and the relationship between stages.'],['Five-card spread','A simple cross adds nuance by exploring tensions, support, direction and the centre of the issue.']]},
    {slug:'love-tarot', title:'Love Tarot: relationship and emotional readings', description:'Use a Marseille Tarot spread to reflect on relationships, emotional choices and changing dynamics.', h1:'Love Tarot and relationship questions', intro:'A love reading can help you reflect on a relationship, expectation, choice or transition without claiming certainty about another person’s private thoughts or future actions.', sections:[['Ask an open question','Questions focused on your own situation tend to be more useful than yes/no predictions about another person.'],['Cards often significant in love','The Lovers, Empress, Sun, Moon and Devil can carry strong relationship themes depending on surrounding cards.'],['Keep your agency','The reading offers perspective; your choices remain your own.']]},
    {slug:'career-tarot', title:'Career Tarot: work, change and professional choices', description:'Reflect on career decisions, professional change and work dynamics with the Marseille Tarot.', h1:'Career Tarot and professional choices', intro:'Tarot can provide a structured way to reflect on priorities, obstacles, resources and options during a professional transition.', sections:[['Career questions','Focus on context, resources and possible directions rather than expecting a guaranteed forecast.'],['Professional symbolism','The Chariot may suggest momentum, the Emperor structure, the Wheel change and the World completion.'],['Not professional advice','Symbolic guidance never replaces qualified legal, tax, financial or career advice where that is required.']]},
    {slug:'tarot-reader', title:'Private online Tarot consultation with Nanou', description:'Continue your reading in a private online consultation with Nanou when the service is available.', h1:'Private Tarot consultation with Nanou', intro:'When private consultation is open, you can continue your reading with Nanou and explore your question in greater depth. Pricing is always shown before payment.', sections:[['Personalised discussion','The consultation can build on your question and selected cards to explore themes in more depth.'],['Availability','Private chat may be closed when Nanou is unavailable. No private-chat payment can be made while it is closed.'],['Transparent pricing','Price, duration and any renewal mechanism are displayed before checkout.']]}
  ]
}

export const ARCANA = [
['le-mat','the-fool','Le Mat','The Fool','nouveau départ, liberté et confiance dans le mouvement','beginnings, freedom and trust in movement'],
['le-bateleur','the-magician','Le Bateleur','The Magician','initiative, potentiel et capacité d’agir','initiative, potential and the ability to act'],
['la-papesse','the-high-priestess','La Papesse','The High Priestess','intuition, intériorité et connaissance silencieuse','intuition, inner awareness and quiet knowledge'],
['limperatrice','the-empress','L’Impératrice','The Empress','créativité, expression et fécondité','creativity, expression and growth'],
['lempereur','the-emperor','L’Empereur','The Emperor','structure, stabilité et autorité','structure, stability and authority'],
['le-pape','the-hierophant','Le Pape','The Hierophant','transmission, valeurs et conseil','tradition, values and guidance'],
['les-amoureux','the-lovers','Les Amoureux','The Lovers','choix, relation et alignement','choice, relationship and alignment'],
['le-chariot','the-chariot','Le Chariot','The Chariot','élan, direction et volonté','momentum, direction and willpower'],
['la-justice','justice','La Justice','Justice','équilibre, responsabilité et décision','balance, responsibility and decision'],
['lhermite','the-hermit','L’Hermite','The Hermit','recul, recherche et maturité','reflection, search and maturity'],
['la-roue-de-fortune','wheel-of-fortune','La Roue de Fortune','Wheel of Fortune','cycle, changement et opportunité','cycles, change and opportunity'],
['la-force','strength','La Force','Strength','maîtrise intérieure, courage et constance','inner strength, courage and steadiness'],
['le-pendu','the-hanged-man','Le Pendu','The Hanged Man','pause, renversement de perspective et lâcher-prise','pause, changed perspective and surrender'],
['larcane-sans-nom','death','L’Arcane sans nom','Death','transformation, fin de cycle et renouvellement','transformation, endings and renewal'],
['temperance','temperance','Tempérance','Temperance','équilibre, adaptation et circulation','balance, adaptation and flow'],
['le-diable','the-devil','Le Diable','The Devil','désir, attachement et puissance instinctive','desire, attachment and instinctive power'],
['la-maison-dieu','the-tower','La Maison Dieu','The Tower','rupture, révélation et restructuration','disruption, revelation and restructuring'],
['letoile','the-star','L’Étoile','The Star','espoir, confiance et inspiration','hope, trust and inspiration'],
['la-lune','the-moon','La Lune','The Moon','intuition, imaginaire et incertitude','intuition, imagination and uncertainty'],
['le-soleil','the-sun','Le Soleil','The Sun','clarté, vitalité et joie partagée','clarity, vitality and shared joy'],
['le-jugement','judgement','Le Jugement','Judgement','réveil, appel et nouvelle compréhension','awakening, calling and new understanding'],
['le-monde','the-world','Le Monde','The World','accomplissement, intégration et ouverture','completion, integration and expansion']
]

export function getSeoPage(lang, slug){
  const intent=(INTENT_PAGES[lang]||[]).find(p=>p.slug===slug); if(intent) return {...intent,type:'intent'}
  const arc=ARCANA.find(a => (lang==='fr'?a[0]:a[1])===slug); if(!arc) return null
  const name=lang==='fr'?arc[2]:arc[3], theme=lang==='fr'?arc[4]:arc[5]
  return lang==='fr' ? {type:'arcana',slug,title:`${name} : signification au Tarot de Marseille`,description:`Découvrez la signification de ${name} au Tarot de Marseille : symbolique, amour, travail et lecture dans un tirage.`,h1:`${name} au Tarot de Marseille`,intro:`${name} est un arcane majeur associé à ${theme}. Sa signification dépend toujours de la question, de sa position et des cartes qui l’entourent.`,sections:[['Signification générale',`Dans une lecture, ${name} invite à observer les thèmes de ${theme}. Il peut signaler une dynamique déjà présente ou une attitude à développer.`],['En amour',`Sur le plan sentimental, ${name} se lit en relation avec la qualité du lien, les attentes et la capacité à agir avec lucidité. La carte ne permet pas de connaître avec certitude les pensées d’un tiers.`],['Dans le travail',`Dans un contexte professionnel, ${name} peut éclairer les ressources, tensions ou transformations associées à votre question. Une lecture de tarot ne remplace pas un conseil professionnel.`]]} : {type:'arcana',slug,title:`${name}: Marseille Tarot meaning`,description:`Explore the meaning of ${name} in Marseille Tarot, including relationships, career themes and its role in a spread.`,h1:`${name} in Marseille Tarot`,intro:`${name} is a Major Arcana card associated with ${theme}. Its meaning depends on the question, its position and the surrounding cards.`,sections:[['General meaning',`In a reading, ${name} highlights themes of ${theme}. It may describe an existing dynamic or an attitude worth developing.`],['Love and relationships',`In relationship questions, ${name} should be read alongside the quality of the bond, expectations and personal agency. It cannot reveal another person’s private thoughts with certainty.`],['Career and work',`In a professional context, ${name} can help frame resources, tensions or change around your question. Tarot does not replace qualified professional advice.`]]}
}

export function allSeoUrls(){
  const rows=[]; for(const lang of ['fr','en']){for(const p of INTENT_PAGES[lang]) rows.push(`/${lang}/${p.slug}`); for(const a of ARCANA) rows.push(`/${lang}/${lang==='fr'?a[0]:a[1]}`)} return rows
}
