import Head from 'next/head'
import {useRouter} from 'next/router'

const FR=[
['1. Prestataire des consultations et objet','Les prestations de tarologie proposées sous le nom commercial « Les Tarots de Nanou » sont fournies par Yveline MILEWSKI, entrepreneur individuel — SIREN 897 557 120 — SIRET 897 557 120 00028 — 1055 avenue Rhin et Danube, 06140 Vence, France. Les présentes CGV régissent les tirages, lectures Premium et consultations privées vendus au consommateur par Yveline MILEWSKI.'],
['2. Opérateur technique de la plateforme','INTERFACE-TRUST, EURL au capital de 5 000 €, 296 chemin Clos de Brasset, 06560 Valbonne, France — SIREN 824 105 357 — RCS Grasse 824 105 357 — TVA FR65824105357, fournit l’infrastructure technique du site, les fonctions de mise en relation et les intégrations techniques nécessaires au fonctionnement du service. INTERFACE-TRUST ne réalise aucune consultation de tarot, aucune interprétation divinatoire et ne fournit au client aucun conseil médical, psychologique, juridique, fiscal, financier, patrimonial ou professionnel. Sauf obligation légale impérative contraire, INTERFACE-TRUST n’est pas le prestataire des consultations de tarologie.'],
['3. Nature du service','Le Tarot de Marseille est proposé à des fins de divertissement, de réflexion personnelle et d’interprétation symbolique. Aucune lecture ne constitue une prédiction certaine, un diagnostic médical ou psychologique, ni un conseil juridique, fiscal, financier, patrimonial ou professionnel. Le client demeure seul responsable de ses décisions.'],
['4. Majorité et capacité','Les services payants sont réservés aux personnes âgées de 18 ans ou plus et juridiquement capables de contracter.'],
['5. Lecture Premium','La Lecture Premium est facturée au prix TTC affiché avant la commande. Le paiement rémunère la fourniture de la lecture et non l’obtention d’un résultat déterminé.'],
['6. Consultation privée et renouvellement automatique','La consultation privée coûte 39,90 € TTC pour les 10 premières minutes. Tant qu’elle reste active, elle est automatiquement renouvelée par tranches supplémentaires de 10 minutes facturées 39,90 € TTC chacune. Il ne s’agit pas d’un abonnement. Une minute avant chaque renouvellement, un avertissement et un compte à rebours sont affichés. Le client peut empêcher le débit suivant en utilisant « Terminer la consultation » avant l’échéance. Toute tranche effectivement commencée est due dans son intégralité, sous réserve des droits impératifs du consommateur.'],
['7. Plafond de sécurité','Le renouvellement automatique est limité à quatre tranches au total, soit 40 minutes et 159,60 € TTC maximum par consultation. Au-delà, aucun nouveau débit automatique n’est effectué.'],
['8. Consentement et preuve','Avant paiement, le client accepte séparément les présentes CGV/CGU et le mécanisme de facturation automatique, puis demande expressément l’exécution immédiate. Des éléments techniques de preuve peuvent être conservés : version des conditions, langue, horodatage du consentement, identifiant de paiement, début de session, tranches facturées et fin de consultation.'],
['9. Rétractation','L’exécution débute à la demande expresse du client avant l’expiration du délai légal de rétractation. Les conséquences sur le droit de rétractation sont celles prévues par les dispositions impératives applicables, notamment lorsque le service a été pleinement exécuté après consentement exprès.'],
['10. Paiement et réclamations','Les paiements sont traités au moyen de Stripe. Une transaction refusée peut interrompre la consultation. L’insatisfaction quant à une interprétation ou la non-réalisation d’un événement évoqué ne constitue pas à elle seule un motif de remboursement. Les droits légaux impératifs du consommateur demeurent applicables.'],
['11. Intelligence artificielle','Certaines fonctions techniques peuvent recourir à des systèmes automatisés ou d’intelligence artificielle pour générer, enrichir, structurer ou traduire du contenu. Cela ne transforme pas les interprétations en prédictions certaines ou en conseils professionnels.'],
['12. Utilisation du chat','Les contenus illicites, menaçants, injurieux, discriminatoires, frauduleux ou abusifs sont interdits. Une consultation peut être interrompue en cas de comportement abusif ou illicite.'],
['13. Données personnelles','Les données nécessaires au service peuvent être traitées pour fournir et sécuriser la plateforme et la consultation, traiter les paiements et réclamations, prévenir la fraude et respecter les obligations légales. Les rôles et traitements détaillés doivent être précisés dans la politique de confidentialité du site.'],
['14. Responsabilité','Yveline MILEWSKI est le prestataire des consultations de tarologie. INTERFACE-TRUST intervient comme opérateur et prestataire technique de la plateforme et n’est pas l’auteur des consultations délivrées par la tarologue. Dans les limites permises par la loi, aucune interprétation de tarot ne constitue une garantie de résultat et le client reste responsable de ses décisions. Aucune stipulation ne limite un droit ou une responsabilité que la loi interdit d’exclure ou de limiter.'],
['15. Médiation de la consommation','Après une réclamation écrite préalable adressée à Yveline MILEWSKI et restée sans solution satisfaisante, le consommateur pourra saisir gratuitement le médiateur de la consommation auquel Yveline MILEWSKI aura effectivement adhéré. Si l’adhésion envisagée à CM2C est finalisée, ses coordonnées et modalités de saisine seront publiées ici conformément aux exigences applicables. Aucune affiliation à CM2C n’est revendiquée avant la prise d’effet effective de cette adhésion.'],
['16. Droit applicable et litiges','Les présentes conditions sont soumises au droit français, sans priver un consommateur des protections impératives dont il bénéficie. En cas de litige, les règles légales de compétence juridictionnelle applicables au consommateur demeurent seules applicables ; aucune clause ne peut imposer au consommateur le tribunal de Grasse lorsqu’une règle impérative lui permet de saisir une autre juridiction.'],
['17. Acceptation','La commande nécessite une acceptation explicite des présentes CGV/CGU et, pour la consultation privée, une acceptation distincte du mécanisme de renouvellement automatique. Version : 18 août 2026.']]

const EN=[
['1. Tarot service provider and purpose','Tarot services offered under the trade name “Les Tarots de Nanou” are supplied by Yveline MILEWSKI, sole trader (entrepreneur individuel) — SIREN 897 557 120 — SIRET 897 557 120 00028 — 1055 avenue Rhin et Danube, 06140 Vence, France. These Terms govern Tarot draws, Premium readings and private consultations sold to consumers by Yveline MILEWSKI.'],
['2. Technical platform operator','INTERFACE-TRUST, EURL with share capital of €5,000, 296 chemin Clos de Brasset, 06560 Valbonne, France — SIREN 824 105 357 — RCS Grasse 824 105 357 — VAT FR65824105357, provides the website’s technical infrastructure, matching functions and technical integrations required to operate the service. INTERFACE-TRUST does not perform Tarot consultations or divinatory interpretations and does not provide customers with medical, psychological, legal, tax, financial, investment, wealth-management or professional advice. Except where mandatory law provides otherwise, INTERFACE-TRUST is not the provider of the Tarot consultations.'],
['3. Nature of the service','Tarot de Marseille services are provided for entertainment, personal reflection and symbolic interpretation. They are not guaranteed predictions, medical or psychological diagnoses, or legal, tax, financial, investment, wealth-management or professional advice. Customers remain responsible for their decisions.'],
['4. Eligibility','Paid services are restricted to persons aged 18 or over who have legal capacity to contract.'],
['5. Premium Reading','The Premium Reading is charged at the tax-inclusive price displayed before purchase. Payment is for delivery of the reading, not for a particular outcome.'],
['6. Private consultation and automatic renewal','The private consultation costs €39.90 including taxes for the first 10 minutes. While active, it automatically renews in additional 10-minute blocks charged at €39.90 each. This is not a subscription. One minute before each renewal, a warning and countdown are displayed. The customer can prevent the next charge by selecting “End consultation” before expiry. Each block actually started is payable in full, subject to mandatory consumer rights.'],
['7. Safety cap','Automatic renewal is limited to four blocks in total: 40 minutes and €159.60 including taxes maximum per consultation. No further automatic charge is made beyond this limit.'],
['8. Consent and evidence','Before payment, the customer separately accepts these Terms and the automatic billing mechanism and expressly requests immediate performance. Technical evidence may be retained, including the Terms version, language, consent timestamp, payment identifier, session start, billed blocks and consultation end.'],
['9. Withdrawal','Performance begins at the customer’s express request before expiry of the statutory withdrawal period. The effect on withdrawal rights is governed by mandatory applicable law, including where the service has been fully performed following express consent.'],
['10. Payment and complaints','Payments are processed using Stripe. A declined transaction may interrupt the consultation. Dissatisfaction with an interpretation or the non-occurrence of an event mentioned in a reading does not by itself create a refund entitlement. Mandatory statutory consumer rights remain unaffected.'],
['11. Artificial intelligence','Some technical functions may use automated or artificial-intelligence systems to generate, enrich, structure or translate content. This does not turn symbolic interpretations into guaranteed predictions or professional advice.'],
['12. Chat use','Unlawful, threatening, abusive, discriminatory, fraudulent or otherwise prohibited content is forbidden. A consultation may be terminated in case of abusive or unlawful conduct.'],
['13. Personal data','Data required for the service may be processed to provide and secure the platform and consultation, process payments and complaints, prevent fraud and comply with legal obligations. Detailed roles and processing activities must be specified in the website Privacy Policy.'],
['14. Liability','Yveline MILEWSKI is the provider of the Tarot consultations. INTERFACE-TRUST acts as platform operator and technical service provider and is not the author of consultations delivered by the Tarot practitioner. To the extent permitted by law, no Tarot interpretation constitutes a guarantee of outcome and customers remain responsible for their decisions. Nothing limits any right or liability that applicable law prohibits from being excluded or limited.'],
['15. Consumer mediation','Following an unsuccessful prior written complaint addressed to Yveline MILEWSKI, the consumer may use free consumer mediation through the mediator to which Yveline MILEWSKI has effectively subscribed. If the contemplated CM2C membership is completed, its contact details and referral procedure will be published here in accordance with applicable requirements. No CM2C affiliation is claimed before that membership actually takes effect.'],
['16. Governing law and disputes','These Terms are governed by French law without depriving consumers of mandatory protections applicable to them. Consumer jurisdiction is determined by mandatory applicable rules; these Terms do not require a consumer to bring proceedings exclusively before the Grasse court where mandatory law permits another competent court.'],
['17. Acceptance','An order requires explicit acceptance of these Terms and, for a private consultation, separate acceptance of the automatic renewal mechanism. Version: 18 August 2026.']]

export default function Conditions(){const r=useRouter();const lang=r.query.lang==='en'?'en':'fr';const data=lang==='en'?EN:FR;return <main className="min-h-screen bg-[#160d1d] text-white px-5 py-10"><Head><title>{lang==='en'?'Terms and Conditions':'CGV / CGU'} — Les Tarots de Nanou</title></Head><article className="max-w-4xl mx-auto"><div className="flex justify-end gap-3"><a href="/conditions?lang=fr">FR</a><a href="/conditions?lang=en">EN</a></div><h1 className="font-serif text-4xl mb-2">{lang==='en'?'Terms and Conditions of Sale and Use':'Conditions Générales de Vente et d’Utilisation'}</h1><p className="text-violet-300 mb-8">{lang==='en'?'Last updated: 18 August 2026':'Dernière mise à jour : 18 août 2026'}</p>{data.map(([h,p])=><section key={h} className="mb-7"><h2 className="font-serif text-2xl text-amber-100">{h}</h2><p className="mt-2 leading-7 text-violet-100">{p}</p></section>)}</article></main>}
