create table if not exists public.chat_sessions_preview (
  id uuid primary key default gen_random_uuid(),
  checkout_session_id text unique not null,
  stripe_customer_id text,
  customer_email text,
  customer_token text unique not null,
  owner_token text unique not null,
  accelerated boolean not null default false,
  status text not null default 'active' check (status in ('active','ended','payment_failed')),
  billing_block integer not null default 1,
  amount_paid integer not null default 3990,
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  owner_notified_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.chat_messages_preview (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.chat_sessions_preview(id) on delete cascade,
  role text not null check (role in ('customer','owner','system')),
  body text not null,
  created_at timestamptz not null default now()
);

create index if not exists chat_messages_preview_session_created_idx
  on public.chat_messages_preview(session_id, created_at);

alter table public.chat_sessions_preview enable row level security;
alter table public.chat_messages_preview enable row level security;

-- No public policies on purpose. Preview chat access is server-side only via the service role key.
